### ISSUE TITLE
kind-on-c should use the images digest in the task file

### ISSUE THREAD

**Issue by hoegaarden** [pivotal-k8s/kind-on-c#6]
Right now the task file [references][1] the task image with its tag. This tag is a [strangely computed thing][2]. This was done, because we couldn't (or didn't know how) pin a container image via its digest. So we created our own digest-like tag and used that.

We now found how to pin an image by its digest 🎉:
```yaml
  [...]
image_resource:
  type: registry-image
  source:
    repository: gcr.io/cf-london-servces-k8s/kind-on-c/kind-on-c
  version:
    digest: sha256:7f5bce3de4ca7b749b0d27f510135b977cd374fb3a0a9f4381cefe466451a610
  [...]  
```

Thus we want to do the following:
- [x] remove the strange [digest-like tag generation][2]
- [x] pin the image by digest (instead of by tag) [in the task file][3]

[1]: https://github.com/pivotal-k8s/kind-on-c/blob/cead7421ec051925e136a4b1cf8d04991cc313d5/kind.yaml#L4-L6
[2]: https://github.com/pivotal-k8s/kind-on-c/blob/cead7421ec051925e136a4b1cf8d04991cc313d5/ci/pipeline.yaml#L181-L184
[3]: https://github.com/pivotal-k8s/kind-on-c/blob/cead7421ec051925e136a4b1cf8d04991cc313d5/ci/pipeline.yaml#L211-L228

Bonus:
- [x] If easily possible, state in the commit message what actually has changed (update of the base image, update of docker image, ...)
